# Generated by Django 5.2.6 on 2025-10-16 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('contrasena', models.CharField(max_length=20)),
                ('referido', models.CharField(blank=True, max_length=100, null=True)),
                ('idInventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.inventario')),
            ],
        ),
    ]
